%% validate_matlab_equivalence.m
% =========================================================================
% 100-Test Numerical Equivalence Validation for MATLAB Codegen Options
% =========================================================================
%
% Loads 100 reference test vectors generated by generate_reference_data.py,
% runs them through each MATLAB-based ShuffleNet V2 implementation, and
% compares outputs against PyTorch reference.
%
% Tests three MATLAB code paths:
%   Option 2: PyTorch Coder support package (loadPyTorchExportedProgram)
%   Option 3: importNetworkFromPyTorch dlnetwork
%   Option 4: importNetworkFromONNX dlnetwork
%
% Metrics computed per test:
%   - Max absolute error
%   - Mean absolute error
%   - RMS error
%   - Relative L2 error (||y_test - y_ref|| / ||y_ref||)
%   - Top-1 class match (boolean)
%   - Top-5 class match (Jaccard similarity)
%   - Cosine similarity of output vectors
%
% Output:
%   - equivalence_results.mat — all results
%   - equivalence_report.csv  — summary table
%   - Console printout of PASS/FAIL per option
%
% Usage:
%   Run from the equivalence_tests/ directory, or set paths accordingly.
% =========================================================================

clear; clc;
fprintf('=================================================================\n');
fprintf(' ShuffleNet V2 — 100-Test Numerical Equivalence Validation\n');
fprintf('=================================================================\n\n');

%% Configuration
NUM_TESTS     = 100;
INPUT_SHAPE   = [3, 224, 224];  % CHW (PyTorch layout)
OUTPUT_SIZE   = 1000;
TOLERANCE_ABS = 1e-5;   % Absolute error threshold for near-exact match
TOLERANCE_REL = 1e-4;   % Relative L2 error threshold

testVectorDir = fullfile(pwd, 'test_vectors');
projectDir    = fileparts(pwd);  % parent of equivalence_tests/

%% Check that test vectors exist
if ~isfolder(testVectorDir)
    error('Test vectors not found at: %s\nRun generate_reference_data.py first.', ...
        testVectorDir);
end

%% Load reference metadata
metaFile = fullfile(testVectorDir, 'test_metadata.json');
if isfile(metaFile)
    metaText = fileread(metaFile);
    metadata = jsondecode(metaText);
    fprintf('Reference data: %d tests, PyTorch %s\n', metadata.num_tests, metadata.pytorch_version);
else
    fprintf('WARNING: test_metadata.json not found, proceeding anyway\n');
end

%% Load all reference outputs (stacked binary)
fprintf('\nLoading reference outputs...\n');
refOutputFile = fullfile(testVectorDir, 'all_outputs_100x1000.bin');
refInputFile  = fullfile(testVectorDir, 'all_inputs_100x3x224x224.bin');

if isfile(refOutputFile) && isfile(refInputFile)
    % Fast path: load stacked binaries
    fid = fopen(refOutputFile, 'r', 'l');  % little-endian
    refOutputs = fread(fid, [OUTPUT_SIZE, NUM_TESTS], 'float32');  % 1000 x 100
    fclose(fid);
    refOutputs = refOutputs';  % now 100 x 1000

    fid = fopen(refInputFile, 'r', 'l');
    refInputsRaw = fread(fid, [prod(INPUT_SHAPE), NUM_TESTS], 'float32');
    fclose(fid);
    % refInputsRaw is (150528 x 100), each column is one input in CHW order
    fprintf('  Loaded %d reference inputs and outputs\n', NUM_TESTS);
else
    % Slow path: load individual files
    fprintf('  Loading individual .bin files...\n');
    refOutputs  = zeros(NUM_TESTS, OUTPUT_SIZE, 'single');
    refInputsRaw = zeros(prod(INPUT_SHAPE), NUM_TESTS, 'single');
    for i = 1:NUM_TESTS
        inFile  = fullfile(testVectorDir, sprintf('input_%03d.bin', i));
        outFile = fullfile(testVectorDir, sprintf('output_%03d.bin', i));
        fid = fopen(inFile, 'r', 'l');
        refInputsRaw(:, i) = fread(fid, prod(INPUT_SHAPE), 'float32');
        fclose(fid);
        fid = fopen(outFile, 'r', 'l');
        refOutputs(i, :) = fread(fid, OUTPUT_SIZE, 'float32');
        fclose(fid);
    end
end

%% ===================================================================
%  Prepare results storage
%  ===================================================================
optionNames = {'Option2_PyTorchCoder', 'Option3_importPyTorch', 'Option4_importONNX'};
numOptions  = numel(optionNames);

% Pre-allocate results structure
results = struct();
for oi = 1:numOptions
    oName = optionNames{oi};
    results.(oName).maxAbsErr   = nan(NUM_TESTS, 1);
    results.(oName).meanAbsErr  = nan(NUM_TESTS, 1);
    results.(oName).rmsErr      = nan(NUM_TESTS, 1);
    results.(oName).relL2Err    = nan(NUM_TESTS, 1);
    results.(oName).cosineSim   = nan(NUM_TESTS, 1);
    results.(oName).top1Match   = false(NUM_TESTS, 1);
    results.(oName).top5Jaccard = nan(NUM_TESTS, 1);
    results.(oName).inferTimeMs = nan(NUM_TESTS, 1);
    results.(oName).success     = false;
    results.(oName).errorMsg    = '';
end

%% Helper function: compute equivalence metrics
    function metrics = computeMetrics(yRef, yTest)
        diff = double(yTest(:)) - double(yRef(:));
        metrics.maxAbsErr  = max(abs(diff));
        metrics.meanAbsErr = mean(abs(diff));
        metrics.rmsErr     = sqrt(mean(diff.^2));
        refNorm = norm(double(yRef(:)));
        if refNorm > 0
            metrics.relL2Err = norm(diff) / refNorm;
        else
            metrics.relL2Err = norm(diff);
        end
        % Cosine similarity
        a = double(yRef(:));
        b = double(yTest(:));
        metrics.cosineSim = dot(a, b) / (norm(a) * norm(b) + eps);
        % Top-1 match
        [~, ref1]  = max(yRef);
        [~, test1] = max(yTest);
        metrics.top1Match = (ref1 == test1);
        % Top-5 Jaccard
        [~, refIdx]  = sort(double(yRef(:)),  'descend');
        [~, testIdx] = sort(double(yTest(:)), 'descend');
        ref5  = refIdx(1:5);
        test5 = testIdx(1:5);
        inter = numel(intersect(ref5, test5));
        union = numel(union(ref5, test5));
        metrics.top5Jaccard = inter / union;
    end

%% ===================================================================
%  OPTION 2: PyTorch Coder Support Package
%  ===================================================================
fprintf('\n─────────────────────────────────────────────────────────────\n');
fprintf(' Option 2: PyTorch Coder Support Package\n');
fprintf('─────────────────────────────────────────────────────────────\n');

try
    opt2Dir = fullfile(projectDir, 'option2_pytorch_coder');
    modelFile = fullfile(projectDir, 'shufflenet_exported.pt2');

    % Load model
    fprintf('  Loading PyTorch ExportedProgram...\n');
    net2 = loadPyTorchExportedProgram(modelFile);

    for i = 1:NUM_TESTS
        % Reshape input from flat CHW to 1x3x224x224
        inputCHW = reshape(refInputsRaw(:, i), INPUT_SHAPE);
        inputBCHW = reshape(inputCHW, [1, INPUT_SHAPE]);  % add batch dim

        tic;
        outTest = net2.invoke(inputBCHW);
        results.Option2_PyTorchCoder.inferTimeMs(i) = toc * 1000;

        outTest = squeeze(double(outTest));
        yRef = refOutputs(i, :);

        m = computeMetrics(yRef, outTest);
        results.Option2_PyTorchCoder.maxAbsErr(i)   = m.maxAbsErr;
        results.Option2_PyTorchCoder.meanAbsErr(i)  = m.meanAbsErr;
        results.Option2_PyTorchCoder.rmsErr(i)      = m.rmsErr;
        results.Option2_PyTorchCoder.relL2Err(i)    = m.relL2Err;
        results.Option2_PyTorchCoder.cosineSim(i)   = m.cosineSim;
        results.Option2_PyTorchCoder.top1Match(i)   = m.top1Match;
        results.Option2_PyTorchCoder.top5Jaccard(i) = m.top5Jaccard;

        if mod(i, 25) == 0
            fprintf('    Test %3d/100: maxErr=%.2e, relL2=%.2e, top1=%s\n', ...
                i, m.maxAbsErr, m.relL2Err, mat2str(m.top1Match));
        end
    end
    results.Option2_PyTorchCoder.success = true;
    fprintf('  Option 2 COMPLETE\n');
catch ME
    fprintf('  Option 2 FAILED: %s\n', ME.message);
    results.Option2_PyTorchCoder.errorMsg = ME.message;
end

%% ===================================================================
%  OPTION 3: importNetworkFromPyTorch dlnetwork
%  ===================================================================
fprintf('\n─────────────────────────────────────────────────────────────\n');
fprintf(' Option 3: importNetworkFromPyTorch dlnetwork\n');
fprintf('─────────────────────────────────────────────────────────────\n');

try
    opt3Dir = fullfile(projectDir, 'option3_import_pytorch');
    matFile = fullfile(opt3Dir, 'shufflenet_dlnetwork.mat');

    if isfile(matFile)
        fprintf('  Loading saved dlnetwork from .mat...\n');
        loaded = load(matFile, 'net');
        net3 = loaded.net;
    else
        fprintf('  Importing from PyTorch (this may take a moment)...\n');
        addpath(opt3Dir);
        net3 = importNetworkFromPyTorch(...
            fullfile(projectDir, 'shufflenet_exported.pt2'), ...
            PyTorchInputSizes=[1 3 224 224]);
    end

    for i = 1:NUM_TESTS
        % PyTorch CHW → MATLAB SSCB: permute (C,H,W) → (H,W,C) then add batch
        inputCHW = reshape(refInputsRaw(:, i), INPUT_SHAPE);  % 3x224x224
        inputHWC = permute(inputCHW, [2, 3, 1]);  % 224x224x3
        dlIn = dlarray(single(inputHWC), 'SSCB');

        tic;
        dlOut = predict(net3, dlIn);
        results.Option3_importPyTorch.inferTimeMs(i) = toc * 1000;

        outTest = squeeze(double(extractdata(dlOut)));
        yRef = refOutputs(i, :);

        m = computeMetrics(yRef, outTest);
        results.Option3_importPyTorch.maxAbsErr(i)   = m.maxAbsErr;
        results.Option3_importPyTorch.meanAbsErr(i)  = m.meanAbsErr;
        results.Option3_importPyTorch.rmsErr(i)      = m.rmsErr;
        results.Option3_importPyTorch.relL2Err(i)    = m.relL2Err;
        results.Option3_importPyTorch.cosineSim(i)   = m.cosineSim;
        results.Option3_importPyTorch.top1Match(i)   = m.top1Match;
        results.Option3_importPyTorch.top5Jaccard(i) = m.top5Jaccard;

        if mod(i, 25) == 0
            fprintf('    Test %3d/100: maxErr=%.2e, relL2=%.2e, top1=%s\n', ...
                i, m.maxAbsErr, m.relL2Err, mat2str(m.top1Match));
        end
    end
    results.Option3_importPyTorch.success = true;
    fprintf('  Option 3 COMPLETE\n');
catch ME
    fprintf('  Option 3 FAILED: %s\n', ME.message);
    results.Option3_importPyTorch.errorMsg = ME.message;
end

%% ===================================================================
%  OPTION 4: importNetworkFromONNX dlnetwork
%  ===================================================================
fprintf('\n─────────────────────────────────────────────────────────────\n');
fprintf(' Option 4: importNetworkFromONNX dlnetwork\n');
fprintf('─────────────────────────────────────────────────────────────\n');

try
    opt4Dir = fullfile(projectDir, 'option4_onnx_import');
    matFile = fullfile(opt4Dir, 'shufflenet_onnx_dlnetwork.mat');

    if isfile(matFile)
        fprintf('  Loading saved dlnetwork from .mat...\n');
        loaded = load(matFile, 'net');
        net4 = loaded.net;
    else
        fprintf('  Importing from ONNX (this may take a moment)...\n');
        addpath(opt4Dir);
        onnxFile = fullfile(opt4Dir, 'shufflenet_v2.onnx');
        net4 = importNetworkFromONNX(onnxFile, ...
            InputDataFormats='BCSS', ...
            OutputDataFormats='BC');
    end

    for i = 1:NUM_TESTS
        % For ONNX-imported network, input format depends on network config
        % Try SSCB format (H,W,C,B) which is standard MATLAB image layout
        inputCHW = reshape(refInputsRaw(:, i), INPUT_SHAPE);  % 3x224x224
        inputHWC = permute(inputCHW, [2, 3, 1]);  % 224x224x3
        dlIn = dlarray(single(inputHWC), 'SSCB');

        tic;
        dlOut = predict(net4, dlIn);
        results.Option4_importONNX.inferTimeMs(i) = toc * 1000;

        outTest = squeeze(double(extractdata(dlOut)));
        yRef = refOutputs(i, :);

        m = computeMetrics(yRef, outTest);
        results.Option4_importONNX.maxAbsErr(i)   = m.maxAbsErr;
        results.Option4_importONNX.meanAbsErr(i)  = m.meanAbsErr;
        results.Option4_importONNX.rmsErr(i)      = m.rmsErr;
        results.Option4_importONNX.relL2Err(i)    = m.relL2Err;
        results.Option4_importONNX.cosineSim(i)   = m.cosineSim;
        results.Option4_importONNX.top1Match(i)   = m.top1Match;
        results.Option4_importONNX.top5Jaccard(i) = m.top5Jaccard;

        if mod(i, 25) == 0
            fprintf('    Test %3d/100: maxErr=%.2e, relL2=%.2e, top1=%s\n', ...
                i, m.maxAbsErr, m.relL2Err, mat2str(m.top1Match));
        end
    end
    results.Option4_importONNX.success = true;
    fprintf('  Option 4 COMPLETE\n');
catch ME
    fprintf('  Option 4 FAILED: %s\n', ME.message);
    results.Option4_importONNX.errorMsg = ME.message;
end

%% ===================================================================
%  Generate Summary Report
%  ===================================================================
fprintf('\n=================================================================\n');
fprintf(' EQUIVALENCE TEST SUMMARY (100 tests per option)\n');
fprintf('=================================================================\n\n');

fprintf('%-28s %12s %12s %12s %8s %8s\n', ...
    'Option', 'Max|Err|', 'Mean|Err|', 'RelL2', 'Top1%', 'Cos Sim');
fprintf('%s\n', repmat('-', 1, 80));

summaryTable = {};
for oi = 1:numOptions
    oName = optionNames{oi};
    r = results.(oName);

    if r.success
        maxE  = max(r.maxAbsErr);
        meanE = mean(r.meanAbsErr);
        relL2 = mean(r.relL2Err);
        top1  = sum(r.top1Match) / NUM_TESTS * 100;
        cosS  = mean(r.cosineSim);
        avgMs = mean(r.inferTimeMs);

        % Determine PASS/FAIL
        if maxE < 1e-3 && relL2 < 1e-3
            status = 'PASS';
        elseif maxE < 1e-1 && relL2 < 1e-2
            status = 'MARGINAL';
        else
            status = 'FAIL';
        end

        fprintf('%-28s %12.2e %12.2e %12.2e %7.1f%% %8.6f  [%s] (%.1f ms avg)\n', ...
            oName, maxE, meanE, relL2, top1, cosS, status, avgMs);

        summaryTable{end+1, 1} = oName;
        summaryTable{end, 2} = maxE;
        summaryTable{end, 3} = meanE;
        summaryTable{end, 4} = relL2;
        summaryTable{end, 5} = top1;
        summaryTable{end, 6} = cosS;
        summaryTable{end, 7} = status;
        summaryTable{end, 8} = avgMs;
    else
        fprintf('%-28s %12s %12s %12s %8s %8s  [SKIPPED: %s]\n', ...
            oName, 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', r.errorMsg);
        summaryTable{end+1, 1} = oName;
        summaryTable{end, 2} = NaN;
        summaryTable{end, 3} = NaN;
        summaryTable{end, 4} = NaN;
        summaryTable{end, 5} = NaN;
        summaryTable{end, 6} = NaN;
        summaryTable{end, 7} = 'SKIPPED';
        summaryTable{end, 8} = NaN;
    end
end

%% Per-category breakdown
fprintf('\n─── Breakdown by Test Category ────────────────────────────────\n');
categories = {
    'Normal Random (1-50)',    1:50;
    'Uniform [0,1] (51-70)',  51:70;
    'Edge Cases (71-80)',     71:80;
    'Patterns (81-90)',       81:90;
    'ImageNet-like (91-100)', 91:100;
};

for oi = 1:numOptions
    oName = optionNames{oi};
    r = results.(oName);
    if ~r.success, continue; end

    fprintf('\n  %s:\n', oName);
    fprintf('  %-26s %12s %12s %8s\n', 'Category', 'MaxAbsErr', 'RelL2Err', 'Top1%');
    for ci = 1:size(categories, 1)
        catName = categories{ci, 1};
        catIdx  = categories{ci, 2};
        fprintf('  %-26s %12.2e %12.2e %7.1f%%\n', ...
            catName, ...
            max(r.maxAbsErr(catIdx)), ...
            mean(r.relL2Err(catIdx)), ...
            sum(r.top1Match(catIdx)) / numel(catIdx) * 100);
    end
end

%% Save results
fprintf('\n─── Saving Results ───────────────────────────────────────────\n');

% Save .mat
save(fullfile(pwd, 'equivalence_results.mat'), 'results', 'optionNames', ...
    'categories', 'summaryTable', '-v7.3');
fprintf('  Saved: equivalence_results.mat\n');

% Save CSV report
csvFile = fullfile(pwd, 'equivalence_report.csv');
fid = fopen(csvFile, 'w');
fprintf(fid, 'Option,MaxAbsErr,MeanAbsErr,RelL2Err,Top1_Pct,CosineSim,Status,AvgInferMs\n');
for si = 1:size(summaryTable, 1)
    fprintf(fid, '%s,%.6e,%.6e,%.6e,%.1f,%.8f,%s,%.2f\n', ...
        summaryTable{si, 1}, summaryTable{si, 2}, summaryTable{si, 3}, ...
        summaryTable{si, 4}, summaryTable{si, 5}, summaryTable{si, 6}, ...
        summaryTable{si, 7}, summaryTable{si, 8});
end
fclose(fid);
fprintf('  Saved: equivalence_report.csv\n');

%% Per-test detailed CSV
detailCsv = fullfile(pwd, 'equivalence_detail.csv');
fid = fopen(detailCsv, 'w');
fprintf(fid, 'TestID');
for oi = 1:numOptions
    oName = optionNames{oi};
    fprintf(fid, ',%s_MaxAbsErr,%s_RelL2,%s_CosSim,%s_Top1Match,%s_InferMs', ...
        oName, oName, oName, oName, oName);
end
fprintf(fid, '\n');

for i = 1:NUM_TESTS
    fprintf(fid, '%d', i);
    for oi = 1:numOptions
        oName = optionNames{oi};
        r = results.(oName);
        if r.success
            fprintf(fid, ',%.6e,%.6e,%.8f,%d,%.2f', ...
                r.maxAbsErr(i), r.relL2Err(i), r.cosineSim(i), ...
                r.top1Match(i), r.inferTimeMs(i));
        else
            fprintf(fid, ',NaN,NaN,NaN,NaN,NaN');
        end
    end
    fprintf(fid, '\n');
end
fclose(fid);
fprintf('  Saved: equivalence_detail.csv\n');

fprintf('\n=================================================================\n');
fprintf(' Equivalence validation complete!\n');
fprintf('=================================================================\n');
