/*
 * validate_c_equivalence.c
 * =========================================================================
 * 100-Test Numerical Equivalence Validation for Hand-Crafted C (Option 1)
 * =========================================================================
 *
 * Loads 100 reference test vectors (generated by generate_reference_data.py),
 * runs each through the hand-crafted ShuffleNet V2 C implementation, and
 * compares outputs against PyTorch reference.
 *
 * Metrics per test:
 *   - Max absolute error
 *   - Mean absolute error
 *   - RMS error
 *   - Relative L2 error
 *   - Top-1 class match
 *   - Top-5 Jaccard similarity
 *   - Cosine similarity
 *
 * Build (host):
 *   gcc -O2 -o validate_c validate_c_equivalence.c \
 *       ../option1_handcrafted_c/shufflenet_v2.c -lm \
 *       -I../option1_handcrafted_c
 *
 * Usage:
 *   ./validate_c [test_vectors_dir]
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <float.h>
#include <time.h>

/* Include the hand-crafted ShuffleNet implementation */
#include "../option1_handcrafted_c/shufflenet_v2.h"

/* ── Configuration ─────────────────────────────────────────────────── */
#define NUM_TESTS       100
#define INPUT_SIZE      150528   /* 1 * 3 * 224 * 224 */
#define OUTPUT_SIZE     1000
#define TOP_K           5
#define PASS_THRESHOLD  1e-3     /* Max absolute error for PASS */
#define WARN_THRESHOLD  1e-1     /* Max absolute error for MARGINAL */

/* ── Test Categories ───────────────────────────────────────────────── */
typedef struct {
    const char *name;
    int start;  /* 1-indexed */
    int end;    /* 1-indexed, inclusive */
} TestCategory;

static const TestCategory categories[] = {
    {"Normal Random",    1,  50},
    {"Uniform [0,1]",   51, 70},
    {"Edge Cases",       71, 80},
    {"Patterns",         81, 90},
    {"ImageNet-like",    91, 100},
};
#define NUM_CATEGORIES  (sizeof(categories) / sizeof(categories[0]))

/* ── Per-test metrics ──────────────────────────────────────────────── */
typedef struct {
    double max_abs_err;
    double mean_abs_err;
    double rms_err;
    double rel_l2_err;
    double cosine_sim;
    int    top1_match;
    double top5_jaccard;
    double infer_time_ms;
} TestMetrics;

/* ── Helper: find top-K indices ────────────────────────────────────── */
static void top_k_indices(const float *arr, int n, int k, int *indices) {
    /* Simple selection: find k largest */
    int used[OUTPUT_SIZE] = {0};
    for (int ki = 0; ki < k; ki++) {
        float best = -FLT_MAX;
        int best_idx = 0;
        for (int i = 0; i < n; i++) {
            if (!used[i] && arr[i] > best) {
                best = arr[i];
                best_idx = i;
            }
        }
        indices[ki] = best_idx;
        used[best_idx] = 1;
    }
}

/* ── Helper: compute Jaccard similarity of two sets ────────────────── */
static double jaccard(const int *a, const int *b, int k) {
    int inter = 0;
    for (int i = 0; i < k; i++) {
        for (int j = 0; j < k; j++) {
            if (a[i] == b[j]) {
                inter++;
                break;
            }
        }
    }
    /* Union = 2*k - intersection (assuming no duplicates within each set) */
    int uni = 2 * k - inter;
    return (double)inter / (double)uni;
}

/* ── Compute metrics between reference and test output ─────────────── */
static TestMetrics compute_metrics(const float *ref, const float *test, int n) {
    TestMetrics m;
    double sum_abs = 0.0, sum_sq = 0.0;
    double max_abs = 0.0;
    double dot_ab = 0.0, norm_a = 0.0, norm_b = 0.0;
    double norm_diff = 0.0, norm_ref = 0.0;

    for (int i = 0; i < n; i++) {
        double a = (double)ref[i];
        double b = (double)test[i];
        double d = fabs(b - a);

        if (d > max_abs) max_abs = d;
        sum_abs += d;
        sum_sq  += d * d;
        dot_ab  += a * b;
        norm_a  += a * a;
        norm_b  += b * b;
        norm_diff += (b - a) * (b - a);
        norm_ref  += a * a;
    }

    m.max_abs_err  = max_abs;
    m.mean_abs_err = sum_abs / n;
    m.rms_err      = sqrt(sum_sq / n);
    m.rel_l2_err   = (norm_ref > 0) ? sqrt(norm_diff) / sqrt(norm_ref) : sqrt(norm_diff);
    m.cosine_sim   = dot_ab / (sqrt(norm_a) * sqrt(norm_b) + 1e-30);

    /* Top-1 match */
    int ref_top1 = 0, test_top1 = 0;
    float ref_max = ref[0], test_max = test[0];
    for (int i = 1; i < n; i++) {
        if (ref[i] > ref_max)  { ref_max = ref[i];   ref_top1 = i; }
        if (test[i] > test_max) { test_max = test[i]; test_top1 = i; }
    }
    m.top1_match = (ref_top1 == test_top1) ? 1 : 0;

    /* Top-5 Jaccard */
    int ref5[TOP_K], test5[TOP_K];
    top_k_indices(ref, n, TOP_K, ref5);
    top_k_indices(test, n, TOP_K, test5);
    m.top5_jaccard = jaccard(ref5, test5, TOP_K);

    return m;
}

/* ── Load binary float32 file ──────────────────────────────────────── */
static int load_float_binary(const char *path, float *buf, int count) {
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "ERROR: Cannot open %s\n", path);
        return -1;
    }
    size_t read = fread(buf, sizeof(float), count, f);
    fclose(f);
    if ((int)read != count) {
        fprintf(stderr, "ERROR: Expected %d floats, got %zu from %s\n",
                count, read, path);
        return -1;
    }
    return 0;
}

/* ── Main ──────────────────────────────────────────────────────────── */
int main(int argc, char *argv[]) {
    const char *test_dir = (argc > 1) ? argv[1] : "test_vectors";

    printf("=================================================================\n");
    printf(" ShuffleNet V2 — 100-Test C Equivalence Validation (Option 1)\n");
    printf("=================================================================\n\n");

    /* Allocate buffers */
    float *input_buf  = (float *)malloc(INPUT_SIZE * sizeof(float));
    float *output_buf = (float *)malloc(OUTPUT_SIZE * sizeof(float));
    float *ref_output = (float *)malloc(OUTPUT_SIZE * sizeof(float));
    TestMetrics all_metrics[NUM_TESTS];

    if (!input_buf || !output_buf || !ref_output) {
        fprintf(stderr, "ERROR: Memory allocation failed\n");
        return 1;
    }

    /* Initialize the ShuffleNet model (load weights, allocate scratch) */
    printf("Initializing ShuffleNet V2 C implementation...\n");
    ShuffleNetV2 model;
    if (shufflenet_v2_init(&model) != 0) {
        fprintf(stderr, "ERROR: Model initialization failed\n");
        fprintf(stderr, "NOTE: Ensure weight files are accessible.\n");
        free(input_buf); free(output_buf); free(ref_output);
        return 1;
    }
    printf("  Model initialized successfully\n\n");

    /* Run all 100 tests */
    int pass_count = 0, marginal_count = 0, fail_count = 0;
    int load_errors = 0;
    double total_infer_ms = 0.0;

    for (int t = 0; t < NUM_TESTS; t++) {
        char in_path[512], out_path[512];
        snprintf(in_path,  sizeof(in_path),  "%s/input_%03d.bin",  test_dir, t + 1);
        snprintf(out_path, sizeof(out_path), "%s/output_%03d.bin", test_dir, t + 1);

        /* Load input and reference output */
        if (load_float_binary(in_path, input_buf, INPUT_SIZE) != 0 ||
            load_float_binary(out_path, ref_output, OUTPUT_SIZE) != 0) {
            load_errors++;
            continue;
        }

        /* Run inference */
        struct timespec t0, t1;
        clock_gettime(CLOCK_MONOTONIC, &t0);
        shufflenet_v2_forward(&model, input_buf, output_buf);
        clock_gettime(CLOCK_MONOTONIC, &t1);

        double dt_ms = (t1.tv_sec - t0.tv_sec) * 1000.0 +
                       (t1.tv_nsec - t0.tv_nsec) / 1e6;

        /* Compute metrics */
        TestMetrics m = compute_metrics(ref_output, output_buf, OUTPUT_SIZE);
        m.infer_time_ms = dt_ms;
        all_metrics[t] = m;
        total_infer_ms += dt_ms;

        /* Classify result */
        if (m.max_abs_err < PASS_THRESHOLD && m.rel_l2_err < PASS_THRESHOLD) {
            pass_count++;
        } else if (m.max_abs_err < WARN_THRESHOLD) {
            marginal_count++;
        } else {
            fail_count++;
        }

        /* Progress reporting */
        if ((t + 1) % 10 == 0 || m.max_abs_err > WARN_THRESHOLD) {
            const char *status = (m.max_abs_err < PASS_THRESHOLD) ? "PASS" :
                                 (m.max_abs_err < WARN_THRESHOLD) ? "MARG" : "FAIL";
            printf("  Test %3d: maxErr=%.2e  relL2=%.2e  cos=%.6f  top1=%s  [%s]  %.1fms\n",
                   t + 1, m.max_abs_err, m.rel_l2_err, m.cosine_sim,
                   m.top1_match ? "Y" : "N", status, dt_ms);
        }
    }

    if (load_errors > 0) {
        printf("\nWARNING: %d test files could not be loaded\n", load_errors);
    }

    int tests_run = NUM_TESTS - load_errors;

    /* ── Summary ───────────────────────────────────────────────────── */
    printf("\n=================================================================\n");
    printf(" RESULTS SUMMARY — Option 1 (Hand-Crafted C)\n");
    printf("=================================================================\n\n");

    /* Aggregate metrics */
    double worst_max = 0, sum_mean = 0, sum_rel = 0, sum_cos = 0;
    int top1_correct = 0;
    double sum_jaccard = 0;

    for (int t = 0; t < NUM_TESTS; t++) {
        TestMetrics *m = &all_metrics[t];
        if (m->max_abs_err > worst_max) worst_max = m->max_abs_err;
        sum_mean += m->mean_abs_err;
        sum_rel  += m->rel_l2_err;
        sum_cos  += m->cosine_sim;
        top1_correct += m->top1_match;
        sum_jaccard  += m->top5_jaccard;
    }

    printf("  Tests run:         %d / %d\n", tests_run, NUM_TESTS);
    printf("  PASS:              %d\n", pass_count);
    printf("  MARGINAL:          %d\n", marginal_count);
    printf("  FAIL:              %d\n", fail_count);
    printf("\n");
    printf("  Worst max|err|:    %.6e\n", worst_max);
    printf("  Avg mean|err|:     %.6e\n", sum_mean / tests_run);
    printf("  Avg rel L2 err:    %.6e\n", sum_rel / tests_run);
    printf("  Avg cosine sim:    %.8f\n", sum_cos / tests_run);
    printf("  Top-1 accuracy:    %d/%d (%.1f%%)\n",
           top1_correct, tests_run, 100.0 * top1_correct / tests_run);
    printf("  Avg Top-5 Jaccard: %.4f\n", sum_jaccard / tests_run);
    printf("  Avg inference:     %.2f ms\n", total_infer_ms / tests_run);
    printf("  Total time:        %.2f s\n", total_infer_ms / 1000.0);

    /* ── Per-category breakdown ────────────────────────────────────── */
    printf("\n─── Breakdown by Test Category ────────────────────────────\n");
    printf("  %-22s %12s %12s %8s\n", "Category", "MaxAbsErr", "AvgRelL2", "Top1%");

    for (int c = 0; c < (int)NUM_CATEGORIES; c++) {
        double cat_max = 0, cat_rel = 0;
        int cat_top1 = 0, cat_n = 0;
        for (int t = categories[c].start - 1; t < categories[c].end; t++) {
            TestMetrics *m = &all_metrics[t];
            if (m->max_abs_err > cat_max) cat_max = m->max_abs_err;
            cat_rel += m->rel_l2_err;
            cat_top1 += m->top1_match;
            cat_n++;
        }
        printf("  %-22s %12.2e %12.2e %7.1f%%\n",
               categories[c].name, cat_max, cat_rel / cat_n,
               100.0 * cat_top1 / cat_n);
    }

    /* ── Write CSV report ──────────────────────────────────────────── */
    const char *csv_path = "c_equivalence_detail.csv";
    FILE *csv = fopen(csv_path, "w");
    if (csv) {
        fprintf(csv, "TestID,MaxAbsErr,MeanAbsErr,RMSErr,RelL2Err,"
                     "CosineSim,Top1Match,Top5Jaccard,InferTimeMs\n");
        for (int t = 0; t < NUM_TESTS; t++) {
            TestMetrics *m = &all_metrics[t];
            fprintf(csv, "%d,%.8e,%.8e,%.8e,%.8e,%.10f,%d,%.4f,%.3f\n",
                    t + 1, m->max_abs_err, m->mean_abs_err, m->rms_err,
                    m->rel_l2_err, m->cosine_sim, m->top1_match,
                    m->top5_jaccard, m->infer_time_ms);
        }
        fclose(csv);
        printf("\n  CSV report saved: %s\n", csv_path);
    }

    /* ── Overall verdict ───────────────────────────────────────────── */
    printf("\n=================================================================\n");
    if (fail_count == 0 && marginal_count == 0) {
        printf(" OVERALL: PASS — All %d tests within tolerance (%.0e)\n",
               tests_run, PASS_THRESHOLD);
    } else if (fail_count == 0) {
        printf(" OVERALL: MARGINAL — %d tests above tight tolerance, "
               "0 failures\n", marginal_count);
    } else {
        printf(" OVERALL: FAIL — %d test(s) exceeded tolerance\n", fail_count);
    }
    printf("=================================================================\n");

    /* Cleanup */
    shufflenet_v2_free(&model);
    free(input_buf);
    free(output_buf);
    free(ref_output);

    return (fail_count > 0) ? 1 : 0;
}
