classdef ChannelShuffleLayer < nnet.layer.Layer
    %ChannelShuffleLayer  Codegen-compatible channel shuffle for ShuffleNet V2.
    %
    %   Performs: reshape(C -> [groups, C/groups]) -> transpose -> flatten
    %   Input:  SSCB dlarray of size [H, W, C, N]
    %   Output: SSCB dlarray of size [H, W, C, N] with channels interleaved
    %
    %   This replaces the AutogeneratedFromPyTorch view_view layers that
    %   importNetworkFromPyTorch generates for channel shuffle operations.
    %
    %   Example:
    %       layer = ChannelShuffleLayer(2, 'shuffle_stage2');
    %
    %   Copyright 2026. Codegen-compatible replacement for Option 3.

    %#codegen

    properties
        NumGroups (1,1) double = 2
    end

    methods
        function layer = ChannelShuffleLayer(numGroups, name)
            %ChannelShuffleLayer Construct channel shuffle layer.
            %   layer = ChannelShuffleLayer(numGroups, name)
            arguments
                numGroups (1,1) double = 2
                name string = ""
            end
            layer.Name = name;
            layer.NumGroups = numGroups;
            layer.Description = sprintf("Channel shuffle (groups=%d)", numGroups);
        end

        function Z = predict(layer, X)
            %predict  Forward pass: channel shuffle.
            %   X is [H, W, C, N] (unformatted inside dlnetwork).
            %   Output Z is [H, W, C, N] with channels interleaved.

            G = layer.NumGroups;

            sz = size(X);
            H = sz(1); W = sz(2); C = sz(3);
            if numel(sz) >= 4
                N = sz(4);
            else
                N = 1;
            end
            CperG = C / G;

            % Reshape: [H, W, C, N] -> [H, W, CperG, G, N]
            Xr = reshape(X, [H, W, CperG, G, N]);

            % Permute: swap G and CperG dims -> [H, W, G, CperG, N]
            Xp = permute(Xr, [1, 2, 4, 3, 5]);

            % Flatten back: [H, W, G, CperG, N] -> [H, W, C, N]
            Z = reshape(Xp, [H, W, C, N]);
        end
    end
end
