classdef ChannelSplitLayer < nnet.layer.Layer
    %ChannelSplitLayer  Codegen-compatible channel split (chunk) for ShuffleNet V2.
    %
    %   Splits the channel dimension into 2 equal halves.
    %   Input:  SSCB dlarray of size [H, W, C, N]
    %   Output: Two SSCB dlarrays of size [H, W, C/2, N]
    %
    %   This replaces the AutogeneratedFromPyTorch chunk layers that
    %   importNetworkFromPyTorch generates for channel split operations.
    %
    %   Example:
    %       layer = ChannelSplitLayer('split_stage2_1');
    %
    %   Copyright 2026. Codegen-compatible replacement for Option 3.

    %#codegen

    properties (Constant)
        NumChunks = 2
    end

    methods
        function layer = ChannelSplitLayer(name)
            %ChannelSplitLayer Construct channel split layer.
            arguments
                name string = ""
            end
            layer.Name = name;
            layer.NumOutputs = 2;
            layer.Description = "Channel split (2 chunks along channel dim)";
        end

        function [Z1, Z2] = predict(~, X)
            %predict  Forward pass: split channels in half.
            %   X is [H, W, C, N] (unformatted inside dlnetwork).
            %   Z1 is [H, W, C/2, N] (first half)
            %   Z2 is [H, W, C/2, N] (second half)

            C = size(X, 3);
            half = C / 2;

            Z1 = X(:, :, 1:half, :);
            Z2 = X(:, :, half+1:C, :);
        end
    end
end
