%% Option 5: Rebuild dlnetwork with Codegen-Compatible Custom Layers
% =========================================================================
% Takes the dlnetwork imported by Option 3 (importNetworkFromPyTorch) and
% replaces all 30 AutogeneratedFromPyTorch custom layers with codegen-
% compatible equivalents:
%
%   - 16 view_view layers  -> ChannelShuffleLayer (groups=2)
%   - 13 chunk layers      -> ChannelSplitLayer (2 outputs)
%   -  1 mean layer        -> globalAveragePooling2dLayer
%
% The rebuilt network produces bit-identical output to the original but
% supports MATLAB Coder C code generation.
%
% Prerequisites:
%   - option3_import_pytorch/shufflenet_dlnetwork.mat must exist
%   - MATLAB R2026a with Deep Learning Toolbox, MATLAB Coder, Embedded Coder
%
% Copyright 2026. Option 5 for ARM Cortex-A embedded deployment.
% =========================================================================

clear; clc;
fprintf('=============================================================\n');
fprintf(' Option 5: Rebuild dlnetwork for Codegen Compatibility\n');
fprintf(' Replace AutogeneratedFromPyTorch -> codegen-compatible layers\n');
fprintf('=============================================================\n\n');

scriptDir = fileparts(mfilename('fullpath'));
projectDir = fullfile(scriptDir, '..');
addpath(scriptDir);  % For ChannelShuffleLayer, ChannelSplitLayer

%% Phase 1: Import model fresh (avoids .mat loading issues with custom classes)
fprintf('--- Phase 1: Import Model Fresh ---\n');

% Add Option 3's custom layer path so the import machinery works
opt3Dir = fullfile(projectDir, 'option3_import_pytorch');
addpath(opt3Dir);

modelFile = fullfile(projectDir, 'shufflenet_exported.pt2');
if ~isfile(modelFile)
    error('Model not found: %s', modelFile);
end

fprintf('  Importing from PyTorch (this takes ~30s)...\n');
tImport = tic;
netOrig = importNetworkFromPyTorch(modelFile, ...
    PyTorchInputSizes=[1 3 224 224], ...
    Namespace='shufflenet_exported');
importTime = toc(tImport);
fprintf('  Import completed in %.1f s\n', importTime);

% Expand NetworkLayer containers to expose individual layers
fprintf('  Expanding layers...\n');
netOrig = expandLayers(netOrig);
fprintf('  After expansion: %d layers\n', numel(netOrig.Layers));
fprintf('  Loaded network with %d layers\n', numel(netOrig.Layers));

% Identify custom layers to replace
layerNames = {netOrig.Layers.Name};
viewLayers = layerNames(contains(layerNames, 'view_view'));
chunkLayers = layerNames(contains(layerNames, 'chunk'));
meanLayers = layerNames(contains(layerNames, 'mean') & ...
    ~contains(layerNames, 'conv') & ~contains(layerNames, 'bn') & ...
    ~contains(layerNames, 'relu') & ~contains(layerNames, 'pool'));

fprintf('  Found %d view_view layers (channel shuffle)\n', numel(viewLayers));
fprintf('  Found %d chunk layers (channel split)\n', numel(chunkLayers));
fprintf('  Found %d mean layers (global avg pool)\n', numel(meanLayers));
fprintf('  Total custom layers to replace: %d\n', ...
    numel(viewLayers) + numel(chunkLayers) + numel(meanLayers));

%% Phase 2: Replace custom layers
fprintf('\n--- Phase 2: Replace Custom Layers ---\n');

net = netOrig;

% Replace view_view layers with ChannelShuffleLayer
for i = 1:numel(viewLayers)
    name = viewLayers{i};
    newLayer = ChannelShuffleLayer(2, name);
    net = replaceLayer(net, name, newLayer);
    fprintf('  Replaced %s -> ChannelShuffleLayer\n', name);
end

% Replace chunk layers with ChannelSplitLayer
for i = 1:numel(chunkLayers)
    name = chunkLayers{i};
    newLayer = ChannelSplitLayer(name);
    net = replaceLayer(net, name, newLayer);
    fprintf('  Replaced %s -> ChannelSplitLayer\n', name);
end

% Replace mean layer with globalAveragePooling2dLayer.
% The original mean layer computes mean over spatial dims AND squeezes,
% producing [C, N]. globalAveragePooling2dLayer produces [1, 1, C, N].
% The FC layer after it has OperationDimension set for PyTorch order.
% We need to insert a flattenLayer between GAP and FC to match shapes.
for i = 1:numel(meanLayers)
    name = meanLayers{i};
    lgraph = layerGraph(net);

    % Find the layer connected after the mean layer
    conns = lgraph.Connections;
    srcIdx = strcmp(conns.Source, [name '/out']);
    if ~any(srcIdx)
        % Try without /out suffix
        srcIdx = startsWith(conns.Source, name);
    end

    gapName = name;
    flatName = [name '_flatten'];

    % Replace mean with GAP
    gapLayer = globalAveragePooling2dLayer('Name', gapName);
    lgraph = replaceLayer(lgraph, name, gapLayer);

    % Insert flattenLayer after GAP and before FC
    flatLayer = flattenLayer('Name', flatName);
    lgraph = addLayers(lgraph, flatLayer);

    % Reconnect: GAP -> flatten -> FC
    % Find what GAP connects to
    conns2 = lgraph.Connections;
    gapOutIdx = startsWith(conns2.Source, gapName);
    if any(gapOutIdx)
        destLayer = conns2.Destination{find(gapOutIdx, 1)};
        lgraph = disconnectLayers(lgraph, [gapName '/out'], destLayer);
        lgraph = connectLayers(lgraph, [gapName '/out'], [flatName '/in']);
        lgraph = connectLayers(lgraph, [flatName '/out'], destLayer);
    end

    fprintf('  Replaced %s -> globalAveragePooling2dLayer + flattenLayer\n', name);
end

% Fix FC layer OperationDimension — the imported FC layer has
% OperationDimension set for PyTorch convention. After replacing the mean
% layer (which originally squeezed spatial dims + permuted to PyTorch order),
% we now have standard MATLAB dimension ordering. Reset OperationDimension.
fcLayers = lgraph.Layers(arrayfun(@(l) isa(l, 'nnet.cnn.layer.FullyConnectedLayer'), lgraph.Layers));
for i = 1:numel(fcLayers)
    fcOld = fcLayers(i);
    fprintf('  Fixing FC layer "%s" OperationDimension\n', fcOld.Name);
    % Create a new FC layer with default OperationDimension
    fcNew = fullyConnectedLayer(fcOld.OutputSize, 'Name', fcOld.Name, ...
        'Weights', fcOld.Weights, 'Bias', fcOld.Bias);
    lgraph = replaceLayer(lgraph, fcOld.Name, fcNew);
end

net = dlnetwork(lgraph);
fprintf('\n  Rebuilt network: %d layers\n', numel(net.Layers));

%% Phase 3: Verify numerical equivalence
fprintf('\n--- Phase 3: Verify Numerical Equivalence ---\n');

rng(42);
testInput = dlarray(single(randn(224, 224, 3)), 'SSCB');

% Run both networks
yOrig = predict(netOrig, testInput);
yNew  = predict(net, testInput);

yOrig = squeeze(double(extractdata(yOrig)));
yNew  = squeeze(double(extractdata(yNew)));

maxErr = max(abs(yOrig(:) - yNew(:)));
cosine = dot(yOrig(:), yNew(:)) / (norm(yOrig(:)) * norm(yNew(:)));
[~, top1_orig] = max(yOrig);
[~, top1_new]  = max(yNew);

fprintf('  Max absolute error: %.2e\n', maxErr);
fprintf('  Cosine similarity:  %.10f\n', cosine);
fprintf('  Top-1 match:        %s (orig=%d, new=%d)\n', ...
    mat2str(top1_orig == top1_new), top1_orig, top1_new);

if maxErr < 1e-5
    fprintf('  STATUS: PASS — Bit-accurate rebuild\n');
elseif maxErr < 1e-2
    fprintf('  STATUS: PASS — Numerically equivalent\n');
else
    fprintf('  STATUS: WARNING — Significant differences detected\n');
end

%% Phase 4: Check codegen compatibility
fprintf('\n--- Phase 4: Check Codegen Compatibility ---\n');

try
    result = analyzeNetworkForCodegen(net, ...
        TargetLibrary='none', ...
        TargetDevice='cpu');
    if result.Supported
        fprintf('  analyzeNetworkForCodegen: SUPPORTED for library-free C\n');
    else
        fprintf('  analyzeNetworkForCodegen: NOT SUPPORTED\n');
        disp(result.NetworkDiagnostics);
        disp(result.LayerDiagnostics);
    end
catch ME
    fprintf('  analyzeNetworkForCodegen failed: %s\n', ME.message);
    fprintf('  Proceeding with codegen attempt anyway...\n');
end

%% Phase 5: Save rebuilt network
fprintf('\n--- Phase 5: Save Network ---\n');
save(fullfile(scriptDir, 'shufflenet_v5_dlnetwork.mat'), 'net', '-v7.3');
fprintf('  Saved: shufflenet_v5_dlnetwork.mat\n');

%% Phase 6: Generate MEX for validation
fprintf('\n--- Phase 6: Generate MEX ---\n');
inputType = coder.typeof(single(0), [224 224 3 1], [false false false false]);

try
    tStart = tic;
    mexDir = fullfile(scriptDir, 'mexOutputDir');
    cfg = coder.config('mex');
    cfg.TargetLang = 'C';
    cfg.SIMDAcceleration = 'full';  % Expert fix #3: SIMD for best MEX perf
    cfg.DeepLearningConfig = coder.DeepLearningConfig('none');

    codegen -config cfg ...
        -d mexDir ...
        predict_shufflenet_v5 ...
        -args {inputType} ...
        -report
    mexTime = toc(tStart);
    fprintf('  MEX generation SUCCESS in %.1f seconds\n', mexTime);
catch ME
    mexTime = toc(tStart);
    fprintf('  MEX generation FAILED (%.1f s): %s\n', mexTime, ME.message);
end

%% Phase 7: Generate Embedded C code
fprintf('\n--- Phase 7: Generate Embedded C ---\n');

try
    tStart = tic;
    embeddedDir = fullfile(scriptDir, 'embeddedDir');
    cfg = coder.config('lib', 'ecoder', true);
    cfg.TargetLang = 'C';
    cfg.GenerateReport = true;
    cfg.GenCodeOnly = true;

    % Deep learning config (library-free)
    dlcfg = coder.DeepLearningConfig('none');
    cfg.DeepLearningConfig = dlcfg;

    % Expert fix #1: NEON SIMD (property of cfg, not dlcfg)
    cfg.InstructionSetExtensions = 'Neon v7';

    % Expert fix #2: valid Embedded Coder hardware name
    try
        cfg.Hardware = coder.hardware('Raspberry Pi');
    catch
        fprintf('  (Raspberry Pi support package not installed, using GenCodeOnly)\n');
    end

    % Expert fix #4: weights in binary files
    cfg.LargeConstantThreshold = 0;

    % Expert fix #5: multi-core Cortex-A53
    cfg.EnableOpenMP = true;

    codegen -config cfg ...
        -d embeddedDir ...
        predict_shufflenet_v5 ...
        -args {inputType} ...
        -report
    codegenTime = toc(tStart);
    fprintf('  Embedded C generation SUCCESS in %.1f seconds\n', codegenTime);

    % Report metrics
    cFiles = dir(fullfile(embeddedDir, '**', '*.c'));
    hFiles = dir(fullfile(embeddedDir, '**', '*.h'));
    totalSize = sum([cFiles.bytes]) + sum([hFiles.bytes]);
    fprintf('  Generated %d .c files, %d .h files (%.1f KB total)\n', ...
        numel(cFiles), numel(hFiles), totalSize / 1024);
catch ME
    codegenTime = toc(tStart);
    fprintf('  Embedded C generation FAILED (%.1f s): %s\n', codegenTime, ME.message);
end

%% Summary
fprintf('\n=============================================================\n');
fprintf(' Option 5 Summary\n');
fprintf('=============================================================\n');
fprintf('  Layers replaced:       %d\n', ...
    numel(viewLayers) + numel(chunkLayers) + numel(meanLayers));
fprintf('  Equivalence max error: %.2e\n', maxErr);
fprintf('  Cosine similarity:     %.10f\n', cosine);
fprintf('  Top-1 match:           %s\n', mat2str(top1_orig == top1_new));
fprintf('  MEX generation:        %.1f s\n', mexTime);
if exist('codegenTime', 'var')
    fprintf('  Embedded C generation: %.1f s\n', codegenTime);
end
fprintf('  Output dir:            %s\n', scriptDir);
fprintf('=============================================================\n');
