classdef ShuffleNetV2_stage2_0_view_view_8 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage2_0_view_view_8 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage2_0_view_view_8(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [view_view1output] = predict(obj,view_catoutput)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_catoutput, view_catoutput_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_catoutput, 'BCSS', 4);
            [view_catoutput_numdims] = (int64(4));
            [view_view1output] = tracedPyTorchFunction(obj,view_catoutput,false,"predict");
            [view_view1output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view1output, 4, "BCSS");
        end
        function [view_view1output] = forward(obj,view_catoutput)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_catoutput, view_catoutput_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_catoutput, 'BCSS', 4);
            [view_catoutput_numdims] = (int64(4));
            [view_view1output] = tracedPyTorchFunction(obj,view_catoutput,true,"forward");
            [view_view1output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view1output, 4, "BCSS");
        end
        function [view_view1output] = tracedPyTorchFunction(obj,view_catoutput,isForward,predict)
            [view_viewoutput] = shufflenet_exported.ops.pyView(view_catoutput,[1 2 58 28 28],[4]);
            [transpose_transposeoutput] = shufflenet_exported.ops.pyTranspose(view_viewoutput,1,2,[5]);
            [contiguous_contiguousoutput] = shufflenet_exported.ops.pyIdentity(transpose_transposeoutput);
            [view_view1output] = shufflenet_exported.ops.pyView(contiguous_contiguousoutput,[1 -1 28 28],[5]);
        end
    end
end
