classdef ShuffleNetV2_stage3_1_view_view_10 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage3_1_view_view_10 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage3_1_view_view_10(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [view_view11output] = predict(obj,view_cat5output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat5output, view_cat5output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat5output, 'BCSS', 4);
            [view_cat5output_numdims] = (int64(4));
            [view_view11output] = tracedPyTorchFunction(obj,view_cat5output,false,"predict");
            [view_view11output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view11output, 4, "BCSS");
        end
        function [view_view11output] = forward(obj,view_cat5output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat5output, view_cat5output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat5output, 'BCSS', 4);
            [view_cat5output_numdims] = (int64(4));
            [view_view11output] = tracedPyTorchFunction(obj,view_cat5output,true,"forward");
            [view_view11output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view11output, 4, "BCSS");
        end
        function [view_view11output] = tracedPyTorchFunction(obj,view_cat5output,isForward,predict)
            [view_view10output] = shufflenet_exported.ops.pyView(view_cat5output,[1 2 116 14 14],[4]);
            [transpose_transpose5output] = shufflenet_exported.ops.pyTranspose(view_view10output,1,2,[5]);
            [contiguous_contiguous5output] = shufflenet_exported.ops.pyIdentity(transpose_transpose5output);
            [view_view11output] = shufflenet_exported.ops.pyView(contiguous_contiguous5output,[1 -1 14 14],[5]);
        end
    end
end
