classdef ShuffleNetV2_stage4_0_view_view_10 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage4_0_view_view_10 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:51
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage4_0_view_view_10(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [view_view25output] = predict(obj,view_cat12output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat12output, view_cat12output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat12output, 'BCSS', 4);
            [view_cat12output_numdims] = (int64(4));
            [view_view25output] = tracedPyTorchFunction(obj,view_cat12output,false,"predict");
            [view_view25output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view25output, 4, "BCSS");
        end
        function [view_view25output] = forward(obj,view_cat12output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat12output, view_cat12output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat12output, 'BCSS', 4);
            [view_cat12output_numdims] = (int64(4));
            [view_view25output] = tracedPyTorchFunction(obj,view_cat12output,true,"forward");
            [view_view25output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view25output, 4, "BCSS");
        end
        function [view_view25output] = tracedPyTorchFunction(obj,view_cat12output,isForward,predict)
            [view_view24output] = shufflenet_exported.ops.pyView(view_cat12output,[1 2 232 7 7],[4]);
            [transpose_transpose12output] = shufflenet_exported.ops.pyTranspose(view_view24output,1,2,[5]);
            [contiguous_contiguous12output] = shufflenet_exported.ops.pyIdentity(transpose_transpose12output);
            [view_view25output] = shufflenet_exported.ops.pyView(contiguous_contiguous12output,[1 -1 7 7],[5]);
        end
    end
end
