classdef ShuffleNetV2_stage2_1_view_view_9 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage2_1_view_view_9 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage2_1_view_view_9(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [view_view3output] = predict(obj,view_cat1output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat1output, view_cat1output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat1output, 'BCSS', 4);
            [view_cat1output_numdims] = (int64(4));
            [view_view3output] = tracedPyTorchFunction(obj,view_cat1output,false,"predict");
            [view_view3output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view3output, 4, "BCSS");
        end
        function [view_view3output] = forward(obj,view_cat1output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat1output, view_cat1output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat1output, 'BCSS', 4);
            [view_cat1output_numdims] = (int64(4));
            [view_view3output] = tracedPyTorchFunction(obj,view_cat1output,true,"forward");
            [view_view3output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view3output, 4, "BCSS");
        end
        function [view_view3output] = tracedPyTorchFunction(obj,view_cat1output,isForward,predict)
            [view_view2output] = shufflenet_exported.ops.pyView(view_cat1output,[1 2 58 28 28],[4]);
            [transpose_transpose1output] = shufflenet_exported.ops.pyTranspose(view_view2output,1,2,[5]);
            [contiguous_contiguous1output] = shufflenet_exported.ops.pyIdentity(transpose_transpose1output);
            [view_view3output] = shufflenet_exported.ops.pyView(contiguous_contiguous1output,[1 -1 28 28],[5]);
        end
    end
end
