classdef ShuffleNetV2_stage2_1_chunk_6 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage2_1_chunk_6 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage2_1_chunk_6(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [chunk_getitemoutput, chunk_getitem1output] = predict(obj,chunk_view1output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view1output, chunk_view1output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view1output, 'BCSS', 4);
            [chunk_view1output_numdims] = (int64(4));
            [chunk_getitemoutput, chunk_getitem1output] = tracedPyTorchFunction(obj,chunk_view1output,false,"predict");
            [chunk_getitemoutput] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitemoutput, 4, "BCSS");
            [chunk_getitem1output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem1output, 4, "BCSS");
        end
        function [chunk_getitemoutput, chunk_getitem1output] = forward(obj,chunk_view1output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view1output, chunk_view1output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view1output, 'BCSS', 4);
            [chunk_view1output_numdims] = (int64(4));
            [chunk_getitemoutput, chunk_getitem1output] = tracedPyTorchFunction(obj,chunk_view1output,true,"forward");
            [chunk_getitemoutput] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitemoutput, 4, "BCSS");
            [chunk_getitem1output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem1output, 4, "BCSS");
        end
        function [chunk_getitemoutput, chunk_getitem1output] = tracedPyTorchFunction(obj,chunk_view1output,isForward,predict)
            [chunk_getitemoutput, chunk_getitem1output] = shufflenet_exported.ops.pyChunk(chunk_view1output,2,1,[4]);
        end
    end
end
