classdef ShuffleNetV2_stage4_2_chunk_9 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage4_2_chunk_9 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:51
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage4_2_chunk_9(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [chunk_getitem22output, chunk_getitem23output] = predict(obj,chunk_view27output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view27output, chunk_view27output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view27output, 'BCSS', 4);
            [chunk_view27output_numdims] = (int64(4));
            [chunk_getitem22output, chunk_getitem23output] = tracedPyTorchFunction(obj,chunk_view27output,false,"predict");
            [chunk_getitem22output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem22output, 4, "BCSS");
            [chunk_getitem23output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem23output, 4, "BCSS");
        end
        function [chunk_getitem22output, chunk_getitem23output] = forward(obj,chunk_view27output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view27output, chunk_view27output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view27output, 'BCSS', 4);
            [chunk_view27output_numdims] = (int64(4));
            [chunk_getitem22output, chunk_getitem23output] = tracedPyTorchFunction(obj,chunk_view27output,true,"forward");
            [chunk_getitem22output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem22output, 4, "BCSS");
            [chunk_getitem23output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem23output, 4, "BCSS");
        end
        function [chunk_getitem22output, chunk_getitem23output] = tracedPyTorchFunction(obj,chunk_view27output,isForward,predict)
            [chunk_getitem22output, chunk_getitem23output] = shufflenet_exported.ops.pyChunk(chunk_view27output,2,1,[4]);
        end
    end
end
