classdef ShuffleNetV2_stage3_6_chunk_12 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage3_6_chunk_12 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage3_6_chunk_12(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [chunk_getitem16output, chunk_getitem17output] = predict(obj,chunk_view19output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view19output, chunk_view19output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view19output, 'BCSS', 4);
            [chunk_view19output_numdims] = (int64(4));
            [chunk_getitem16output, chunk_getitem17output] = tracedPyTorchFunction(obj,chunk_view19output,false,"predict");
            [chunk_getitem16output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem16output, 4, "BCSS");
            [chunk_getitem17output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem17output, 4, "BCSS");
        end
        function [chunk_getitem16output, chunk_getitem17output] = forward(obj,chunk_view19output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view19output, chunk_view19output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view19output, 'BCSS', 4);
            [chunk_view19output_numdims] = (int64(4));
            [chunk_getitem16output, chunk_getitem17output] = tracedPyTorchFunction(obj,chunk_view19output,true,"forward");
            [chunk_getitem16output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem16output, 4, "BCSS");
            [chunk_getitem17output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem17output, 4, "BCSS");
        end
        function [chunk_getitem16output, chunk_getitem17output] = tracedPyTorchFunction(obj,chunk_view19output,isForward,predict)
            [chunk_getitem16output, chunk_getitem17output] = shufflenet_exported.ops.pyChunk(chunk_view19output,2,1,[4]);
        end
    end
end
