classdef ShuffleNetV2_stage4_1_chunk_8 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage4_1_chunk_8 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:51
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage4_1_chunk_8(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [chunk_getitem20output, chunk_getitem21output] = predict(obj,chunk_view25output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view25output, chunk_view25output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view25output, 'BCSS', 4);
            [chunk_view25output_numdims] = (int64(4));
            [chunk_getitem20output, chunk_getitem21output] = tracedPyTorchFunction(obj,chunk_view25output,false,"predict");
            [chunk_getitem20output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem20output, 4, "BCSS");
            [chunk_getitem21output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem21output, 4, "BCSS");
        end
        function [chunk_getitem20output, chunk_getitem21output] = forward(obj,chunk_view25output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view25output, chunk_view25output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view25output, 'BCSS', 4);
            [chunk_view25output_numdims] = (int64(4));
            [chunk_getitem20output, chunk_getitem21output] = tracedPyTorchFunction(obj,chunk_view25output,true,"forward");
            [chunk_getitem20output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem20output, 4, "BCSS");
            [chunk_getitem21output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem21output, 4, "BCSS");
        end
        function [chunk_getitem20output, chunk_getitem21output] = tracedPyTorchFunction(obj,chunk_view25output,isForward,predict)
            [chunk_getitem20output, chunk_getitem21output] = shufflenet_exported.ops.pyChunk(chunk_view25output,2,1,[4]);
        end
    end
end
