classdef ShuffleNetV2_mean_7 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_mean_7 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:51
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_mean_7(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [mean_meanoutput] = predict(obj,mean_conv5output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [mean_conv5output, mean_conv5output_format] = shufflenet_exported.ops.permuteToReversePyTorch(mean_conv5output, 'BCSS', 4);
            [mean_conv5output_numdims] = (int64(4));
            [mean_meanoutput] = tracedPyTorchFunction(obj,mean_conv5output,false,"predict");
            %Permute U-labelled output to forward PyTorch dimension ordering
            %Flip dlarray to forward PyTorch ordering
            mean_meanoutput = permute(mean_meanoutput, fliplr(1:max(2,2)));
            mean_meanoutput= dlarray(mean_meanoutput, repmat('U',1,max(2,2)));
        end
        function [mean_meanoutput] = forward(obj,mean_conv5output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [mean_conv5output, mean_conv5output_format] = shufflenet_exported.ops.permuteToReversePyTorch(mean_conv5output, 'BCSS', 4);
            [mean_conv5output_numdims] = (int64(4));
            [mean_meanoutput] = tracedPyTorchFunction(obj,mean_conv5output,true,"forward");
            %Permute U-labelled output to forward PyTorch dimension ordering
            %Flip dlarray to forward PyTorch ordering
            mean_meanoutput = permute(mean_meanoutput, fliplr(1:max(2,2)));
            mean_meanoutput= dlarray(mean_meanoutput, repmat('U',1,max(2,2)));
        end
        function [mean_meanoutput] = tracedPyTorchFunction(obj,mean_conv5output,isForward,predict)
            [mean_meanoutput] = shufflenet_exported.ops.pyMean(mean_conv5output,[2 3],0,[4]);
        end
    end
end
