classdef ShuffleNetV2_stage3_4_view_view_13 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage3_4_view_view_13 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage3_4_view_view_13(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [view_view17output] = predict(obj,view_cat8output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat8output, view_cat8output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat8output, 'BCSS', 4);
            [view_cat8output_numdims] = (int64(4));
            [view_view17output] = tracedPyTorchFunction(obj,view_cat8output,false,"predict");
            [view_view17output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view17output, 4, "BCSS");
        end
        function [view_view17output] = forward(obj,view_cat8output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat8output, view_cat8output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat8output, 'BCSS', 4);
            [view_cat8output_numdims] = (int64(4));
            [view_view17output] = tracedPyTorchFunction(obj,view_cat8output,true,"forward");
            [view_view17output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view17output, 4, "BCSS");
        end
        function [view_view17output] = tracedPyTorchFunction(obj,view_cat8output,isForward,predict)
            [view_view16output] = shufflenet_exported.ops.pyView(view_cat8output,[1 2 116 14 14],[4]);
            [transpose_transpose8output] = shufflenet_exported.ops.pyTranspose(view_view16output,1,2,[5]);
            [contiguous_contiguous8output] = shufflenet_exported.ops.pyIdentity(transpose_transpose8output);
            [view_view17output] = shufflenet_exported.ops.pyView(contiguous_contiguous8output,[1 -1 14 14],[5]);
        end
    end
end
