classdef ShuffleNetV2_stage3_5_chunk_11 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage3_5_chunk_11 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage3_5_chunk_11(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [chunk_getitem14output, chunk_getitem15output] = predict(obj,chunk_view17output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view17output, chunk_view17output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view17output, 'BCSS', 4);
            [chunk_view17output_numdims] = (int64(4));
            [chunk_getitem14output, chunk_getitem15output] = tracedPyTorchFunction(obj,chunk_view17output,false,"predict");
            [chunk_getitem14output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem14output, 4, "BCSS");
            [chunk_getitem15output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem15output, 4, "BCSS");
        end
        function [chunk_getitem14output, chunk_getitem15output] = forward(obj,chunk_view17output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view17output, chunk_view17output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view17output, 'BCSS', 4);
            [chunk_view17output_numdims] = (int64(4));
            [chunk_getitem14output, chunk_getitem15output] = tracedPyTorchFunction(obj,chunk_view17output,true,"forward");
            [chunk_getitem14output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem14output, 4, "BCSS");
            [chunk_getitem15output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem15output, 4, "BCSS");
        end
        function [chunk_getitem14output, chunk_getitem15output] = tracedPyTorchFunction(obj,chunk_view17output,isForward,predict)
            [chunk_getitem14output, chunk_getitem15output] = shufflenet_exported.ops.pyChunk(chunk_view17output,2,1,[4]);
        end
    end
end
