classdef ShuffleNetV2_stage3_2_view_view_11 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %#codegen
    %ShuffleNetV2_stage3_2_view_view_11 Auto-generated custom layer
    % Auto-generated by MATLAB on 20-Mar-2026 21:43:50
    properties (Learnable)
        % Networks (type dlnetwork)
    end
    properties
        % Non-Trainable Parameters
    end
    properties (Learnable)
        % Trainable Parameters
    end
    methods
        function obj = ShuffleNetV2_stage3_2_view_view_11(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end
        function [view_view13output] = predict(obj,view_cat6output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat6output, view_cat6output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat6output, 'BCSS', 4);
            [view_cat6output_numdims] = (int64(4));
            [view_view13output] = tracedPyTorchFunction(obj,view_cat6output,false,"predict");
            [view_view13output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view13output, 4, "BCSS");
        end
        function [view_view13output] = forward(obj,view_cat6output)
            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat6output, view_cat6output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat6output, 'BCSS', 4);
            [view_cat6output_numdims] = (int64(4));
            [view_view13output] = tracedPyTorchFunction(obj,view_cat6output,true,"forward");
            [view_view13output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view13output, 4, "BCSS");
        end
        function [view_view13output] = tracedPyTorchFunction(obj,view_cat6output,isForward,predict)
            [view_view12output] = shufflenet_exported.ops.pyView(view_cat6output,[1 2 116 14 14],[4]);
            [transpose_transpose6output] = shufflenet_exported.ops.pyTranspose(view_view12output,1,2,[5]);
            [contiguous_contiguous6output] = shufflenet_exported.ops.pyIdentity(transpose_transpose6output);
            [view_view13output] = shufflenet_exported.ops.pyView(contiguous_contiguous6output,[1 -1 14 14],[5]);
        end
    end
end
