#!/usr/bin/env python3
"""
export_weights.py — Export ShuffleNet V2 weights to C header files.

Extracts all parameters from the .pt2 model and writes them as C arrays
suitable for embedded deployment. Supports float32 and int8 quantization.

Usage:
    python export_weights.py [--quantize]

Output:
    weights_float32.h  — Full-precision weights
    weights_int8.h     — Quantized int8 weights with per-channel scale factors
    model_config.h     — Architecture constants (channel counts, strides, etc.)
"""

import argparse
import os
import sys
import numpy as np

try:
    import torch
except ImportError:
    print("ERROR: PyTorch is required. Install with: pip install torch")
    sys.exit(1)


def load_model(model_path):
    """Load the exported PyTorch model and extract state dict."""
    print(f"Loading model from {model_path}...")
    ep = torch.export.load(model_path)

    # Collect all named parameters and buffers
    params = {}
    for name, val in ep.named_parameters():
        params[name] = val.detach().cpu().numpy()
    for name, val in ep.named_buffers():
        params[name] = val.detach().cpu().numpy()

    return params


def sanitize_name(name):
    """Convert PyTorch parameter name to valid C identifier."""
    return name.replace(".", "_").replace("-", "_")


def quantize_per_channel(weights, bits=8):
    """
    Quantize weights to int8 using per-output-channel symmetric quantization.
    Returns (quantized_weights, scale_factors).
    """
    if weights.ndim < 2:
        # For biases or 1D params, use global quantization
        abs_max = np.abs(weights).max()
        if abs_max == 0:
            return np.zeros_like(weights, dtype=np.int8), np.float32(1.0)
        scale = abs_max / 127.0
        quantized = np.clip(np.round(weights / scale), -128, 127).astype(np.int8)
        return quantized, np.float32(scale)

    # Per-output-channel quantization (axis 0)
    out_channels = weights.shape[0]
    flat = weights.reshape(out_channels, -1)
    abs_max = np.abs(flat).max(axis=1)
    abs_max[abs_max == 0] = 1.0
    scales = (abs_max / 127.0).astype(np.float32)

    quantized = np.zeros_like(weights, dtype=np.int8)
    for c in range(out_channels):
        quantized[c] = np.clip(
            np.round(weights[c] / scales[c]), -128, 127
        ).astype(np.int8)

    return quantized, scales


def write_array_float32(f, name, data):
    """Write a float32 array to the header file."""
    flat = data.flatten()
    f.write(f"\n/* Shape: {list(data.shape)}, Size: {flat.size} */\n")
    f.write(f"static const float {name}[{flat.size}] = {{\n")

    # Write in rows of 8 values
    for i in range(0, len(flat), 8):
        chunk = flat[i:i+8]
        vals = ", ".join(f"{v:.8e}f" for v in chunk)
        if i + 8 < len(flat):
            f.write(f"    {vals},\n")
        else:
            f.write(f"    {vals}\n")
    f.write("};\n")


def write_array_int8(f, name, data):
    """Write an int8 array to the header file."""
    flat = data.flatten()
    f.write(f"\n/* Shape: {list(data.shape)}, Size: {flat.size} */\n")
    f.write(f"static const int8_t {name}[{flat.size}] = {{\n")

    for i in range(0, len(flat), 16):
        chunk = flat[i:i+16]
        vals = ", ".join(f"{v:4d}" for v in chunk)
        if i + 16 < len(flat):
            f.write(f"    {vals},\n")
        else:
            f.write(f"    {vals}\n")
    f.write("};\n")


def write_scale_array(f, name, scales):
    """Write scale factors for quantized weights."""
    if np.isscalar(scales) or scales.ndim == 0:
        f.write(f"\nstatic const float {name} = {float(scales):.8e}f;\n")
        return
    flat = scales.flatten()
    f.write(f"\n/* Per-channel scale factors, {flat.size} channels */\n")
    f.write(f"static const float {name}[{flat.size}] = {{\n")
    for i in range(0, len(flat), 8):
        chunk = flat[i:i+8]
        vals = ", ".join(f"{v:.8e}f" for v in chunk)
        if i + 8 < len(flat):
            f.write(f"    {vals},\n")
        else:
            f.write(f"    {vals}\n")
    f.write("};\n")


def generate_model_config(params, output_dir):
    """Generate model_config.h with architecture constants."""
    filepath = os.path.join(output_dir, "model_config.h")
    print(f"Writing {filepath}...")

    with open(filepath, "w") as f:
        f.write("/*\n")
        f.write(" * model_config.h — ShuffleNet V2 1.0x Architecture Configuration\n")
        f.write(" * Auto-generated by export_weights.py\n")
        f.write(" *\n")
        f.write(" * Target: STM32F746G-Discovery (ARM Cortex-M7)\n")
        f.write(" */\n\n")
        f.write("#ifndef MODEL_CONFIG_H\n")
        f.write("#define MODEL_CONFIG_H\n\n")

        f.write("/* Input dimensions */\n")
        f.write("#define INPUT_H          224\n")
        f.write("#define INPUT_W          224\n")
        f.write("#define INPUT_C          3\n\n")

        f.write("/* Output dimensions */\n")
        f.write("#define NUM_CLASSES      1000\n\n")

        f.write("/* Stage channel configurations */\n")
        f.write("#define CONV1_OUT_C      24\n")
        f.write("#define STAGE2_OUT_C     116\n")
        f.write("#define STAGE3_OUT_C     232\n")
        f.write("#define STAGE4_OUT_C     464\n")
        f.write("#define CONV5_OUT_C      1024\n\n")

        f.write("/* Stage unit counts */\n")
        f.write("#define STAGE2_UNITS     4\n")
        f.write("#define STAGE3_UNITS     8\n")
        f.write("#define STAGE4_UNITS     4\n\n")

        f.write("/* Feature map sizes after each stage (assuming 224x224 input) */\n")
        f.write("#define FM_AFTER_CONV1   56   /* 224/2/2 = 56 */\n")
        f.write("#define FM_AFTER_STAGE2  28   /* 56/2 = 28 */\n")
        f.write("#define FM_AFTER_STAGE3  14   /* 28/2 = 14 */\n")
        f.write("#define FM_AFTER_STAGE4  7    /* 14/2 = 7 */\n\n")

        f.write("/* Intermediate buffer size (largest feature map in bytes, float32) */\n")
        f.write("#define MAX_FM_SIZE      (CONV1_OUT_C * FM_AFTER_CONV1 * FM_AFTER_CONV1 * 4)\n\n")

        # Calculate total parameter count
        total_params = sum(v.size for k, v in params.items()
                         if "num_batches_tracked" not in k)
        total_bytes_f32 = total_params * 4
        total_bytes_i8 = sum(
            v.size for k, v in params.items()
            if "weight" in k and "num_batches_tracked" not in k
        ) + sum(
            v.size * 4 for k, v in params.items()
            if "weight" not in k and "num_batches_tracked" not in k
        )

        f.write(f"/* Total parameters: {total_params:,} */\n")
        f.write(f"/* Float32 size: {total_bytes_f32:,} bytes ({total_bytes_f32/1024/1024:.2f} MB) */\n")
        f.write(f"/* Int8 quantized estimated size: ~{total_bytes_i8:,} bytes ({total_bytes_i8/1024/1024:.2f} MB) */\n\n")

        f.write("#endif /* MODEL_CONFIG_H */\n")

    print(f"  Total parameters: {total_params:,}")
    print(f"  Float32 size: {total_bytes_f32/1024/1024:.2f} MB")


def generate_weights_header(params, output_dir, quantize=False):
    """Generate weight header file (float32 or int8)."""
    if quantize:
        filepath = os.path.join(output_dir, "weights_int8.h")
        guard = "WEIGHTS_INT8_H"
    else:
        filepath = os.path.join(output_dir, "weights_float32.h")
        guard = "WEIGHTS_FLOAT32_H"

    print(f"Writing {filepath}...")

    with open(filepath, "w") as f:
        f.write("/*\n")
        f.write(f" * {'weights_int8.h' if quantize else 'weights_float32.h'}")
        f.write(" — ShuffleNet V2 1.0x Weights\n")
        f.write(" * Auto-generated by export_weights.py\n")
        f.write(" *\n")
        if quantize:
            f.write(" * Quantization: int8 symmetric per-output-channel\n")
            f.write(" * Biases and BN params remain float32\n")
        f.write(" */\n\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")

        if quantize:
            f.write("#include <stdint.h>\n\n")

        total_size = 0

        # Sort parameters for consistent ordering
        sorted_params = sorted(params.items())

        for name, data in sorted_params:
            if "num_batches_tracked" in name:
                continue  # Skip batch tracking counters

            c_name = sanitize_name(name)

            if quantize and "weight" in name and data.ndim >= 2:
                # Quantize weights to int8
                q_data, scales = quantize_per_channel(data)
                write_array_int8(f, c_name, q_data)
                write_scale_array(f, c_name + "_scale", scales)
                total_size += q_data.size + scales.size * 4
            else:
                # Keep as float32 (biases, BN params, small weights)
                write_array_float32(f, c_name, data)
                total_size += data.size * 4

        f.write(f"\n#endif /* {guard} */\n")

    print(f"  File size will contain ~{total_size:,} bytes of weight data")


def generate_weight_index(params, output_dir):
    """Generate a weight index file documenting all parameters."""
    filepath = os.path.join(output_dir, "weight_index.txt")
    print(f"Writing {filepath}...")

    with open(filepath, "w") as f:
        f.write("ShuffleNet V2 1.0x — Weight Index\n")
        f.write("=" * 60 + "\n\n")
        f.write(f"{'Parameter Name':<55} {'Shape':<25} {'Size':>10}\n")
        f.write("-" * 95 + "\n")

        total = 0
        for name, data in sorted(params.items()):
            if "num_batches_tracked" in name:
                continue
            shape_str = str(list(data.shape))
            f.write(f"{name:<55} {shape_str:<25} {data.size:>10,}\n")
            total += data.size

        f.write("-" * 95 + "\n")
        f.write(f"{'TOTAL':<55} {'':<25} {total:>10,}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Export ShuffleNet V2 weights to C header files"
    )
    parser.add_argument(
        "--quantize", action="store_true",
        help="Also generate int8 quantized weights"
    )
    parser.add_argument(
        "--model", type=str,
        default="../shufflenet_exported.pt2",
        help="Path to the .pt2 model file"
    )
    parser.add_argument(
        "--output-dir", type=str, default=".",
        help="Output directory for generated files"
    )
    args = parser.parse_args()

    # Resolve paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    model_path = os.path.join(script_dir, args.model)
    output_dir = os.path.join(script_dir, args.output_dir)

    if not os.path.exists(model_path):
        print(f"ERROR: Model file not found: {model_path}")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    # Load model and extract parameters
    params = load_model(model_path)

    # Generate outputs
    generate_model_config(params, output_dir)
    generate_weight_index(params, output_dir)
    generate_weights_header(params, output_dir, quantize=False)

    if args.quantize:
        generate_weights_header(params, output_dir, quantize=True)

    print("\nDone! Generated files:")
    print(f"  {output_dir}/model_config.h")
    print(f"  {output_dir}/weight_index.txt")
    print(f"  {output_dir}/weights_float32.h")
    if args.quantize:
        print(f"  {output_dir}/weights_int8.h")


if __name__ == "__main__":
    main()
