classdef ShuffleNetV2_stage3_4_chunk_10 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_4_chunk_10 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:23

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_4_chunk_10(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [chunk_getitem12output, chunk_getitem13output] = predict(obj,chunk_view15output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view15output, chunk_view15output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view15output, 'BCSS', 4);
            [chunk_view15output_numdims] = (int64(4));

            [chunk_getitem12output, chunk_getitem13output] = tracedPyTorchFunction(obj,chunk_view15output,false,"predict");


            [chunk_getitem12output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem12output, 4, "BCSS");
            [chunk_getitem13output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem13output, 4, "BCSS");
        end



        function [chunk_getitem12output, chunk_getitem13output] = forward(obj,chunk_view15output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view15output, chunk_view15output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view15output, 'BCSS', 4);
            [chunk_view15output_numdims] = (int64(4));

            [chunk_getitem12output, chunk_getitem13output] = tracedPyTorchFunction(obj,chunk_view15output,true,"forward");


            [chunk_getitem12output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem12output, 4, "BCSS");
            [chunk_getitem13output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem13output, 4, "BCSS");
        end



        function [chunk_getitem12output, chunk_getitem13output] = tracedPyTorchFunction(obj,chunk_view15output,isForward,predict)
            [chunk_getitem12output, chunk_getitem13output] = shufflenet_exported.ops.pyChunk(chunk_view15output,2,1,[4]);

        end

    end
end

