classdef ShuffleNetV2_stage3_3_view_view_12 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_3_view_view_12 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:23

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_3_view_view_12(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view15output] = predict(obj,view_cat7output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat7output, view_cat7output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat7output, 'BCSS', 4);
            [view_cat7output_numdims] = (int64(4));

            [view_view15output] = tracedPyTorchFunction(obj,view_cat7output,false,"predict");


            [view_view15output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view15output, 4, "BCSS");
        end



        function [view_view15output] = forward(obj,view_cat7output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat7output, view_cat7output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat7output, 'BCSS', 4);
            [view_cat7output_numdims] = (int64(4));

            [view_view15output] = tracedPyTorchFunction(obj,view_cat7output,true,"forward");


            [view_view15output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view15output, 4, "BCSS");
        end



        function [view_view15output] = tracedPyTorchFunction(obj,view_cat7output,isForward,predict)
            [view_view14output] = shufflenet_exported.ops.pyView(view_cat7output,[1 2 116 14 14],[4]);
            [transpose_transpose7output] = shufflenet_exported.ops.pyTranspose(view_view14output,1,2,[5]);
            [contiguous_contiguous7output] = shufflenet_exported.ops.pyIdentity(transpose_transpose7output);
            [view_view15output] = shufflenet_exported.ops.pyView(contiguous_contiguous7output,[1 -1 14 14],[5]);

        end

    end
end

