classdef ShuffleNetV2_stage2_2_chunk_7 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage2_2_chunk_7 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:23

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage2_2_chunk_7(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [chunk_getitem2output, chunk_getitem3output] = predict(obj,chunk_view3output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view3output, chunk_view3output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view3output, 'BCSS', 4);
            [chunk_view3output_numdims] = (int64(4));

            [chunk_getitem2output, chunk_getitem3output] = tracedPyTorchFunction(obj,chunk_view3output,false,"predict");


            [chunk_getitem2output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem2output, 4, "BCSS");
            [chunk_getitem3output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem3output, 4, "BCSS");
        end



        function [chunk_getitem2output, chunk_getitem3output] = forward(obj,chunk_view3output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view3output, chunk_view3output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view3output, 'BCSS', 4);
            [chunk_view3output_numdims] = (int64(4));

            [chunk_getitem2output, chunk_getitem3output] = tracedPyTorchFunction(obj,chunk_view3output,true,"forward");


            [chunk_getitem2output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem2output, 4, "BCSS");
            [chunk_getitem3output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem3output, 4, "BCSS");
        end



        function [chunk_getitem2output, chunk_getitem3output] = tracedPyTorchFunction(obj,chunk_view3output,isForward,predict)
            [chunk_getitem2output, chunk_getitem3output] = shufflenet_exported.ops.pyChunk(chunk_view3output,2,1,[4]);

        end

    end
end

