classdef ShuffleNetV2_stage4_3_view_view_13 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage4_3_view_view_13 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:57

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage4_3_view_view_13(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view31output] = predict(obj,view_cat15output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat15output, view_cat15output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat15output, 'BCSS', 4);
            [view_cat15output_numdims] = (int64(4));

            [view_view31output] = tracedPyTorchFunction(obj,view_cat15output,false,"predict");


            [view_view31output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view31output, 4, "BCSS");
        end



        function [view_view31output] = forward(obj,view_cat15output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat15output, view_cat15output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat15output, 'BCSS', 4);
            [view_cat15output_numdims] = (int64(4));

            [view_view31output] = tracedPyTorchFunction(obj,view_cat15output,true,"forward");


            [view_view31output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view31output, 4, "BCSS");
        end



        function [view_view31output] = tracedPyTorchFunction(obj,view_cat15output,isForward,predict)
            [view_view30output] = shufflenet_exported.ops.pyView(view_cat15output,[1 2 232 7 7],[4]);
            [transpose_transpose15output] = shufflenet_exported.ops.pyTranspose(view_view30output,1,2,[5]);
            [contiguous_contiguous15output] = shufflenet_exported.ops.pyIdentity(transpose_transpose15output);
            [view_view31output] = shufflenet_exported.ops.pyView(contiguous_contiguous15output,[1 -1 7 7],[5]);

        end

    end
end

