classdef ShuffleNetV2_stage4_2_view_view_12 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage4_2_view_view_12 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:24

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage4_2_view_view_12(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view29output] = predict(obj,view_cat14output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat14output, view_cat14output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat14output, 'BCSS', 4);
            [view_cat14output_numdims] = (int64(4));

            [view_view29output] = tracedPyTorchFunction(obj,view_cat14output,false,"predict");


            [view_view29output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view29output, 4, "BCSS");
        end



        function [view_view29output] = forward(obj,view_cat14output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat14output, view_cat14output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat14output, 'BCSS', 4);
            [view_cat14output_numdims] = (int64(4));

            [view_view29output] = tracedPyTorchFunction(obj,view_cat14output,true,"forward");


            [view_view29output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view29output, 4, "BCSS");
        end



        function [view_view29output] = tracedPyTorchFunction(obj,view_cat14output,isForward,predict)
            [view_view28output] = shufflenet_exported.ops.pyView(view_cat14output,[1 2 232 7 7],[4]);
            [transpose_transpose14output] = shufflenet_exported.ops.pyTranspose(view_view28output,1,2,[5]);
            [contiguous_contiguous14output] = shufflenet_exported.ops.pyIdentity(transpose_transpose14output);
            [view_view29output] = shufflenet_exported.ops.pyView(contiguous_contiguous14output,[1 -1 7 7],[5]);

        end

    end
end

