classdef ShuffleNetV2_stage3_7_chunk_13 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_7_chunk_13 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:56

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_7_chunk_13(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [chunk_getitem18output, chunk_getitem19output] = predict(obj,chunk_view21output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view21output, chunk_view21output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view21output, 'BCSS', 4);
            [chunk_view21output_numdims] = (int64(4));

            [chunk_getitem18output, chunk_getitem19output] = tracedPyTorchFunction(obj,chunk_view21output,false,"predict");


            [chunk_getitem18output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem18output, 4, "BCSS");
            [chunk_getitem19output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem19output, 4, "BCSS");
        end



        function [chunk_getitem18output, chunk_getitem19output] = forward(obj,chunk_view21output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view21output, chunk_view21output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view21output, 'BCSS', 4);
            [chunk_view21output_numdims] = (int64(4));

            [chunk_getitem18output, chunk_getitem19output] = tracedPyTorchFunction(obj,chunk_view21output,true,"forward");


            [chunk_getitem18output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem18output, 4, "BCSS");
            [chunk_getitem19output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem19output, 4, "BCSS");
        end



        function [chunk_getitem18output, chunk_getitem19output] = tracedPyTorchFunction(obj,chunk_view21output,isForward,predict)
            [chunk_getitem18output, chunk_getitem19output] = shufflenet_exported.ops.pyChunk(chunk_view21output,2,1,[4]);

        end

    end
end

