classdef ShuffleNetV2_stage3_6_view_view_15 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_6_view_view_15 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:56

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_6_view_view_15(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view21output] = predict(obj,view_cat10output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat10output, view_cat10output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat10output, 'BCSS', 4);
            [view_cat10output_numdims] = (int64(4));

            [view_view21output] = tracedPyTorchFunction(obj,view_cat10output,false,"predict");


            [view_view21output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view21output, 4, "BCSS");
        end



        function [view_view21output] = forward(obj,view_cat10output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat10output, view_cat10output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat10output, 'BCSS', 4);
            [view_cat10output_numdims] = (int64(4));

            [view_view21output] = tracedPyTorchFunction(obj,view_cat10output,true,"forward");


            [view_view21output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view21output, 4, "BCSS");
        end



        function [view_view21output] = tracedPyTorchFunction(obj,view_cat10output,isForward,predict)
            [view_view20output] = shufflenet_exported.ops.pyView(view_cat10output,[1 2 116 14 14],[4]);
            [transpose_transpose10output] = shufflenet_exported.ops.pyTranspose(view_view20output,1,2,[5]);
            [contiguous_contiguous10output] = shufflenet_exported.ops.pyIdentity(transpose_transpose10output);
            [view_view21output] = shufflenet_exported.ops.pyView(contiguous_contiguous10output,[1 -1 14 14],[5]);

        end

    end
end

