classdef ShuffleNetV2_stage3_0_view_view_9 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_0_view_view_9 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:55

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_0_view_view_9(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view9output] = predict(obj,view_cat4output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat4output, view_cat4output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat4output, 'BCSS', 4);
            [view_cat4output_numdims] = (int64(4));

            [view_view9output] = tracedPyTorchFunction(obj,view_cat4output,false,"predict");


            [view_view9output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view9output, 4, "BCSS");
        end



        function [view_view9output] = forward(obj,view_cat4output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat4output, view_cat4output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat4output, 'BCSS', 4);
            [view_cat4output_numdims] = (int64(4));

            [view_view9output] = tracedPyTorchFunction(obj,view_cat4output,true,"forward");


            [view_view9output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view9output, 4, "BCSS");
        end



        function [view_view9output] = tracedPyTorchFunction(obj,view_cat4output,isForward,predict)
            [view_view8output] = shufflenet_exported.ops.pyView(view_cat4output,[1 2 116 14 14],[4]);
            [transpose_transpose4output] = shufflenet_exported.ops.pyTranspose(view_view8output,1,2,[5]);
            [contiguous_contiguous4output] = shufflenet_exported.ops.pyIdentity(transpose_transpose4output);
            [view_view9output] = shufflenet_exported.ops.pyView(contiguous_contiguous4output,[1 -1 14 14],[5]);

        end

    end
end

