classdef ShuffleNetV2_stage2_3_view_view_11 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage2_3_view_view_11 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:23

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage2_3_view_view_11(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view7output] = predict(obj,view_cat3output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat3output, view_cat3output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat3output, 'BCSS', 4);
            [view_cat3output_numdims] = (int64(4));

            [view_view7output] = tracedPyTorchFunction(obj,view_cat3output,false,"predict");


            [view_view7output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view7output, 4, "BCSS");
        end



        function [view_view7output] = forward(obj,view_cat3output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat3output, view_cat3output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat3output, 'BCSS', 4);
            [view_cat3output_numdims] = (int64(4));

            [view_view7output] = tracedPyTorchFunction(obj,view_cat3output,true,"forward");


            [view_view7output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view7output, 4, "BCSS");
        end



        function [view_view7output] = tracedPyTorchFunction(obj,view_cat3output,isForward,predict)
            [view_view6output] = shufflenet_exported.ops.pyView(view_cat3output,[1 2 58 28 28],[4]);
            [transpose_transpose3output] = shufflenet_exported.ops.pyTranspose(view_view6output,1,2,[5]);
            [contiguous_contiguous3output] = shufflenet_exported.ops.pyIdentity(transpose_transpose3output);
            [view_view7output] = shufflenet_exported.ops.pyView(contiguous_contiguous3output,[1 -1 28 28],[5]);

        end

    end
end

