classdef ShuffleNetV2_stage4_1_view_view_11 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage4_1_view_view_11 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:24

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage4_1_view_view_11(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view27output] = predict(obj,view_cat13output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat13output, view_cat13output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat13output, 'BCSS', 4);
            [view_cat13output_numdims] = (int64(4));

            [view_view27output] = tracedPyTorchFunction(obj,view_cat13output,false,"predict");


            [view_view27output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view27output, 4, "BCSS");
        end



        function [view_view27output] = forward(obj,view_cat13output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat13output, view_cat13output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat13output, 'BCSS', 4);
            [view_cat13output_numdims] = (int64(4));

            [view_view27output] = tracedPyTorchFunction(obj,view_cat13output,true,"forward");


            [view_view27output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view27output, 4, "BCSS");
        end



        function [view_view27output] = tracedPyTorchFunction(obj,view_cat13output,isForward,predict)
            [view_view26output] = shufflenet_exported.ops.pyView(view_cat13output,[1 2 232 7 7],[4]);
            [transpose_transpose13output] = shufflenet_exported.ops.pyTranspose(view_view26output,1,2,[5]);
            [contiguous_contiguous13output] = shufflenet_exported.ops.pyIdentity(transpose_transpose13output);
            [view_view27output] = shufflenet_exported.ops.pyView(contiguous_contiguous13output,[1 -1 7 7],[5]);

        end

    end
end

