classdef ShuffleNetV2_stage4_3_chunk_10 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage4_3_chunk_10 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:56

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage4_3_chunk_10(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [chunk_getitem24output, chunk_getitem25output] = predict(obj,chunk_view29output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view29output, chunk_view29output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view29output, 'BCSS', 4);
            [chunk_view29output_numdims] = (int64(4));

            [chunk_getitem24output, chunk_getitem25output] = tracedPyTorchFunction(obj,chunk_view29output,false,"predict");


            [chunk_getitem24output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem24output, 4, "BCSS");
            [chunk_getitem25output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem25output, 4, "BCSS");
        end



        function [chunk_getitem24output, chunk_getitem25output] = forward(obj,chunk_view29output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view29output, chunk_view29output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view29output, 'BCSS', 4);
            [chunk_view29output_numdims] = (int64(4));

            [chunk_getitem24output, chunk_getitem25output] = tracedPyTorchFunction(obj,chunk_view29output,true,"forward");


            [chunk_getitem24output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem24output, 4, "BCSS");
            [chunk_getitem25output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem25output, 4, "BCSS");
        end



        function [chunk_getitem24output, chunk_getitem25output] = tracedPyTorchFunction(obj,chunk_view29output,isForward,predict)
            [chunk_getitem24output, chunk_getitem25output] = shufflenet_exported.ops.pyChunk(chunk_view29output,2,1,[4]);

        end

    end
end

