classdef ShuffleNetV2_stage2_2_view_view_10 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage2_2_view_view_10 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:55

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage2_2_view_view_10(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view5output] = predict(obj,view_cat2output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat2output, view_cat2output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat2output, 'BCSS', 4);
            [view_cat2output_numdims] = (int64(4));

            [view_view5output] = tracedPyTorchFunction(obj,view_cat2output,false,"predict");


            [view_view5output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view5output, 4, "BCSS");
        end



        function [view_view5output] = forward(obj,view_cat2output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat2output, view_cat2output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat2output, 'BCSS', 4);
            [view_cat2output_numdims] = (int64(4));

            [view_view5output] = tracedPyTorchFunction(obj,view_cat2output,true,"forward");


            [view_view5output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view5output, 4, "BCSS");
        end



        function [view_view5output] = tracedPyTorchFunction(obj,view_cat2output,isForward,predict)
            [view_view4output] = shufflenet_exported.ops.pyView(view_cat2output,[1 2 58 28 28],[4]);
            [transpose_transpose2output] = shufflenet_exported.ops.pyTranspose(view_view4output,1,2,[5]);
            [contiguous_contiguous2output] = shufflenet_exported.ops.pyIdentity(transpose_transpose2output);
            [view_view5output] = shufflenet_exported.ops.pyView(contiguous_contiguous2output,[1 -1 28 28],[5]);

        end

    end
end

