classdef ShuffleNetV2_stage3_5_view_view_14 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_5_view_view_14 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:56

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_5_view_view_14(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view19output] = predict(obj,view_cat9output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat9output, view_cat9output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat9output, 'BCSS', 4);
            [view_cat9output_numdims] = (int64(4));

            [view_view19output] = tracedPyTorchFunction(obj,view_cat9output,false,"predict");


            [view_view19output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view19output, 4, "BCSS");
        end



        function [view_view19output] = forward(obj,view_cat9output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat9output, view_cat9output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat9output, 'BCSS', 4);
            [view_cat9output_numdims] = (int64(4));

            [view_view19output] = tracedPyTorchFunction(obj,view_cat9output,true,"forward");


            [view_view19output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view19output, 4, "BCSS");
        end



        function [view_view19output] = tracedPyTorchFunction(obj,view_cat9output,isForward,predict)
            [view_view18output] = shufflenet_exported.ops.pyView(view_cat9output,[1 2 116 14 14],[4]);
            [transpose_transpose9output] = shufflenet_exported.ops.pyTranspose(view_view18output,1,2,[5]);
            [contiguous_contiguous9output] = shufflenet_exported.ops.pyIdentity(transpose_transpose9output);
            [view_view19output] = shufflenet_exported.ops.pyView(contiguous_contiguous9output,[1 -1 14 14],[5]);

        end

    end
end

