classdef ShuffleNetV2_stage3_7_view_view_16 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_7_view_view_16 Auto-generated custom layer
    % Auto-generated by MATLAB on 21-Mar-2026 02:16:24

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_7_view_view_16(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 1;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [view_view23output] = predict(obj,view_cat11output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat11output, view_cat11output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat11output, 'BCSS', 4);
            [view_cat11output_numdims] = (int64(4));

            [view_view23output] = tracedPyTorchFunction(obj,view_cat11output,false,"predict");


            [view_view23output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view23output, 4, "BCSS");
        end



        function [view_view23output] = forward(obj,view_cat11output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [view_cat11output, view_cat11output_format] = shufflenet_exported.ops.permuteToReversePyTorch(view_cat11output, 'BCSS', 4);
            [view_cat11output_numdims] = (int64(4));

            [view_view23output] = tracedPyTorchFunction(obj,view_cat11output,true,"forward");


            [view_view23output] = shufflenet_exported.ops.labelWithPropagatedFormats(view_view23output, 4, "BCSS");
        end



        function [view_view23output] = tracedPyTorchFunction(obj,view_cat11output,isForward,predict)
            [view_view22output] = shufflenet_exported.ops.pyView(view_cat11output,[1 2 116 14 14],[4]);
            [transpose_transpose11output] = shufflenet_exported.ops.pyTranspose(view_view22output,1,2,[5]);
            [contiguous_contiguous11output] = shufflenet_exported.ops.pyIdentity(transpose_transpose11output);
            [view_view23output] = shufflenet_exported.ops.pyView(contiguous_contiguous11output,[1 -1 14 14],[5]);

        end

    end
end

