classdef ShuffleNetV2_stage3_3_chunk_9 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromPyTorch & nnet.layer.Acceleratable
    %ShuffleNetV2_stage3_3_chunk_9 Auto-generated custom layer
    % Auto-generated by MATLAB on 22-Mar-2026 12:37:55

    properties (Learnable)
        % Networks (type dlnetwork)

    end

    properties
        % Non-Trainable Parameters

    end

    properties (Learnable)
        % Trainable Parameters

    end

    methods
        function obj = ShuffleNetV2_stage3_3_chunk_9(Name, Type, InputNames, OutputNames)
            obj.Name = Name;
            obj.Type = Type;
            obj.NumInputs = 1;
            obj.NumOutputs = 2;
            obj.InputNames = InputNames;
            obj.OutputNames = OutputNames;
        end

        function [chunk_getitem10output, chunk_getitem11output] = predict(obj,chunk_view13output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view13output, chunk_view13output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view13output, 'BCSS', 4);
            [chunk_view13output_numdims] = (int64(4));

            [chunk_getitem10output, chunk_getitem11output] = tracedPyTorchFunction(obj,chunk_view13output,false,"predict");


            [chunk_getitem10output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem10output, 4, "BCSS");
            [chunk_getitem11output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem11output, 4, "BCSS");
        end



        function [chunk_getitem10output, chunk_getitem11output] = forward(obj,chunk_view13output)

            %Use the input format inferred by the importer to permute the input into reverse-PyTorch dimension order
            [chunk_view13output, chunk_view13output_format] = shufflenet_exported.ops.permuteToReversePyTorch(chunk_view13output, 'BCSS', 4);
            [chunk_view13output_numdims] = (int64(4));

            [chunk_getitem10output, chunk_getitem11output] = tracedPyTorchFunction(obj,chunk_view13output,true,"forward");


            [chunk_getitem10output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem10output, 4, "BCSS");
            [chunk_getitem11output] = shufflenet_exported.ops.labelWithPropagatedFormats(chunk_getitem11output, 4, "BCSS");
        end



        function [chunk_getitem10output, chunk_getitem11output] = tracedPyTorchFunction(obj,chunk_view13output,isForward,predict)
            [chunk_getitem10output, chunk_getitem11output] = shufflenet_exported.ops.pyChunk(chunk_view13output,2,1,[4]);

        end

    end
end

